# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pr:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'
  displayName: 'Install Node.js'

- script: npm install -g @angular/cli
  displayName: 'Install ng cli'
  
- script: npm install -g yarn
  displayName: 'Install yarn'

- script: yarn
  displayName: 'Install npm dependencies'

- script: yarn lint
  displayName: 'Run lint'

- script: yarn test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  displayName: 'Run tests'

- script: yarn build
  displayName: 'Create prod artifact'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: $(System.DefaultWorkingDirectory)/dist/ll-30-sep-ng-app
    ArtifactName: 'll-30-sep-ng-app'
    publishLocation: 'Container'
  displayName: 'Publish prod artifact'